// <auto-generated />
namespace KhabarYatri.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PublishedDateEdited1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PublishedDateEdited1));
        
        string IMigrationMetadata.Id
        {
            get { return "202009241657265_PublishedDateEdited1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
